---
- name: This playbok will be used
  hosts: test
  tasks:
   - name: This task will install httpd
     yum:
      name: httpd
      state: latest

   - name: This task will copy index.html
     copy:
      src: /myansiblecode/index.html
      dest: /var/www/html
      notify:
       - restart httpd
      tags:
       - H

   - name: This task will be used to start service
     service:
      name: httpd
      state: started
   
   - name: This will be used for restart
     service: 
      name: httpd
      state: restarted
      tags:
       - R
  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
