---
- name: This playbok will be used
  hosts: test
  tasks:
   - name: This task will install httpd
     yum:
      name: httpd
      state: latest

   - name: This task will copy index.html
     copy:
      src: /myansiblecode/index.html
      dest: /var/www/html

 
